name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn
      - run: yarn prettier --check components/**/*.{js,jsx,ts,tsx,}
      - run: yarn prettier --check pages/**/*.{js,jsx,ts,tsx,}
      - run: yarn prettier --check store/**/*.{js,jsx,ts,tsx,}
